### ISSUE TITLE
typed temporal values are not excepted even if they are valid

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#52]
If you type a datetime instead of using the calendar selector, the form marks it as an incorrect format even if it is correct.
![Screen Shot 2022-03-28 at 10 20 30 AM](https://user-images.githubusercontent.com/17934193/160419010-40303fcf-48f5-4a9e-87a7-c040894f5d30.png)

**Comment by Maurier** [comment]
Fixed recently here: https://github.com/cznethub/dspfront/commit/d0931c981624c9cdd47b7aeeaa4f47ec102048ef, https://github.com/cznethub/dspfront/commit/8713827bd3480c509479fa9058721f0e1f76bded

**Comment by devincowan** [comment]
Confirming resolved, but [test_hs_000008_temporal_coverage_persists](https://github.com/CUAHSI/QA-AutomationEngine/blob/master/dsp/dsp.py#L238) is still failing due to #71
