### ISSUE TITLE
my submissions are not initially sorted

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#53]
When I "Finish" a new submission, it takes me to the "My Submissions" page.
The defaults for the dropdown sorts are "Sort by" = Submission Date, and "Order" = Descending
However, the new submission that was just created doesn't show at the top of the list.
The new submission appears after a page refresh or selecting the "sort by" and toggling it.

Not sure if this is an async issue or a sorting issue but seems like people will expect their new submission to show at the top when the page loads.
![Screen Shot 2022-03-28 at 10 23 25 AM](https://user-images.githubusercontent.com/17934193/160420359-8988bfa7-fdfa-45db-b3d4-e6d4ead386f9.png)

**Comment by Maurier** [comment]
Fixed recently here: https://github.com/cznethub/dspfront/commit/cb20b02b46bd714ad2a0eb686cb38a8899f53d05
