### ISSUE TITLE
spatial coverage shouldn't allow invalid limits

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#55]
Unless I'm misunderstanding our box coverage limits, shouldn't these be rejected?
![image](https://user-images.githubusercontent.com/17934193/161783023-495d7873-0154-4688-9b65-bd428f60adc4.png)
This saves to hydroshare without error

**Comment by devincowan** [comment]
related to #19

**Comment by devincowan** [comment]
This is still present as of this writing https://github.com/cznethub/dspfront/commit/7e2c2974708897db47bf149850e46d7155347654
test_hs_000015_invalid_spatial_coverage_rejects

**Comment by sblack-usu** [comment]
We should be able to validate property values against other property values with JSON schema, we shouldn't need to render the map to get this validation.

**Comment by horsburgh** [comment]
The coordinates in the original post save in HydroShare without error. So, HydroShare validates those coordinates just fine. Yes, we should be validating the property values with the JSON schema, but according to HydroShare, these coordinates are valid. Is there actually an issue here?

**Comment by devincowan** [comment]
Sorry I suppose a non-issue if these are valid coords according to HS
