### ISSUE TITLE
URL string 'http://' alone passes front end validation, but fails in back end validation

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#68]
After working on a submission to zenodo, I click "Submit Data" and choose External Repository
Then complete all of the required fields and click "Finish"
Red notification box "Failed to create submission"

In browser console:

'NavigationDuplicated: Avoided redundant navigation to current location: "/submit/zenodo"'
'external: failed to create submission... Unprocessable Entity" 

Probably this 480px vid is too blurry...?
https://user-images.githubusercontent.com/17934193/176980857-43fc78b2-3788-41cd-878f-d8418cc10cc6.mov

Present as of this writing https://github.com/cznethub/dspfront/commit/7e2c2974708897db47bf149850e46d7155347654

**Comment by sblack-usu** [comment]
I'm not able to view the video, something about an invalid type.  @Maurier - are you saying the test is using `http://` only as the url?  If the form renderer isn't validating this url correctly, it isn't validating all other urls correctly, for all repositories.  I don't think updating the json schema regex for all URIs is the correct approach.  The validation in the form library should be fixed.

**Comment by Maurier** [comment]
Yes, the test is using `http://` only as the form value which was passing frontend validation. I've added a more robust regular expression that will make it invalid from now on (https://github.com/cznethub/dspback/pull/95). The test will probably need to be modified.

![image](https://user-images.githubusercontent.com/2448568/177348178-f2b7db82-3867-4c98-ba94-08804fac8b48.png)

**Comment by devincowan** [comment]
resolved testing against https://github.com/cznethub/dspfront/commit/2ef4408e40dfb74d837c9699adaeb7879c843d74
