### ISSUE TITLE
Period Coverage times are shifted

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#71]
When submitting date-time fields to the Hydroshare backend, everything submits fine but if you "Edit" the submission again, the times have all shifted by 4hrs.

Tests caught this for Period Coverage with the Hydroshare backend. But it is possible this issue exists with other date/time fields

https://user-images.githubusercontent.com/17934193/177348379-d2225a63-cbf4-429e-b365-f17c9eb098ca.mov

This test fails
[test_hs_000008_temporal_coverage_persists](https://github.com/CUAHSI/QA-AutomationEngine/blob/master/dsp/dsp.py#L238)
as of https://github.com/cznethub/dspfront/commit/09afde5e818b01e3ca2f03fe23494617a16fda8d

**Comment by Maurier** [comment]
This is happening because we are localizing the value to the user's timezone and storing it as such. I will make changes so that the localized date-time is only used in display, but the underlying value that we store will always be in UTC.
