### ISSUE TITLE
Zenodo Description/Abstract is initially populated with "Undefined"

### ISSUE THREAD

**Issue by devincowan** [cznethub/dspfront#73]
When starting a new Zenodo submission, the Description/Abstract is populated with "Undefined"

https://user-images.githubusercontent.com/17934193/177620695-183bea0d-349c-4a2d-8482-b67fac063d25.mov

[test_ze_000005_required_fields_persist](https://github.com/CUAHSI/QA-AutomationEngine/blob/master/dsp/dsp.py#L803) failing as of 09afde5e818b01e3ca2f03fe23494617a16fda8d

**Comment by Maurier** [comment]
Fixed here: https://github.com/cznethub/dspfront/pull/75

**Comment by devincowan** [comment]
confirmed fixed testing against https://github.com/cznethub/dspfront/commit/2ef4408e40dfb74d837c9699adaeb7879c843d74
